// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: "AIzaSyATqyycQwIxxwMGFj12rR53klcYWMF4YiU",
    authDomain: "buildy-app-31845.firebaseapp.com",
    projectId: "buildy-app-31845",
    storageBucket: "buildy-app-31845.appspot.com",
    messagingSenderId: "1003945532746",
    appId: "1:1003945532746:web:0af23d52e1df85fce4b5b3",
    measurementId: "G-8RB04T9X2V",
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: "AIzaSyDAPpcTbJA1lKpfCE_YTX527RY-M6w3GiU",
    appId: "1:1003945532746:android:5698295a883c8ba0e4b5b3",
    messagingSenderId: "1003945532746",
    projectId: "buildy-app-31845",
    storageBucket: "buildy-app-31845.appspot.com",
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: "your-ios-api-key",
    appId: "your-ios-app-id",
    messagingSenderId: "your-sender-id",
    projectId: "buildy-app-31845",
    storageBucket: "buildy-app-31845.appspot.com",
    iosBundleId: "com.example.buildyApp",
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: "your-ios-api-key",
    appId: "your-ios-app-id",
    messagingSenderId: "your-sender-id",
    projectId: "buildy-app-31845",
    storageBucket: "buildy-app-31845.appspot.com",
    iosBundleId: "com.example.buildyApp",
  );
}
